---
title: "Latihan GGPlot"
output: 
  html_document:
    keep_md: true
---
```{r, echo = FALSE}
knitr::opts_chunk$set(
  fig.path = "Figs/GGPlotFigs-"
)
```


```{r}
library(tidyverse)
data() # to see the list of dataset available
view(msleep)
names(msleep)

```

```{r}
# Bar Charts
msleep   %>%
  drop_na(vore)  %>%
  ggplot(aes(x = vore)) +
  geom_bar(color = "darkslategray", fill = "darkseagreen2", alpha = 0.7) +
  #coord_flip() +
  theme_bw()  +
  labs(x = "Vore",
       y = NULL,
       title = "Number of Observations")

```
```{r}
#Histogram one variable
head(msleep)
msleep   %>%
  ggplot(aes(awake)) +
  geom_histogram(binwidth = 2, color = "darkslategray",
                      fill = "darkseagreen2", alpha = 0.7) +
  theme_bw() +
  labs(x = "Total Sleep",
       y = NULL,
       title = "Histogram of total sleep")
```
```{r}
#Scatter plots with multiple variable
head(mpg)
mpg  %>%
  filter(hwy < 35)  %>%
  ggplot(aes(x = displ,
             y = hwy,
             colour = drv)) +
  geom_point() +
  geom_smooth(method = lm, #linear models
              se = F) + #standard error
  labs(x = "Engine Size",
       y = "MPG on the Highway",
       title = "FUel efficiency") +
  theme_minimal() 


  #stat_density2d() +   #density contour

```

```{r}

#creating a box plot

msleep  %>%
  ggplot(aes(x=vore, y=awake)) +
  geom_boxplot(outlier.colour = "red", outlier.shape = 6) +
  labs(title="test boxplot",
       subtitle = "Data Titanic", caption="Source : Udemy") +
  theme_light()

#+ Geomjitter
msleep  %>%
  ggplot(aes(x=vore, y=awake)) +
  geom_boxplot(outlier.colour = "red", outlier.shape = 6) +
  labs(title="test boxplot",
       subtitle = "Data Titanic", caption="Source : Udemy") +
  theme_light()+
  geom_jitter(width = 0.2, aes(color = sleep_total))

# +facewrap
msleep  %>%
  ggplot(aes(x=conservation, y=awake)) +
  geom_boxplot(outlier.colour = "red", outlier.shape = 6) +
  labs(title="test boxplot",
       subtitle = "Data Msleep", caption="Source : Udemy") +
  theme_light()+
  #geom_jitter(width = 0.2, aes(color = sleep_total)) +
  facet_wrap(~vore) +#dont forget to put ~
  coord_flip() 


```


```{r}
#To save the file
#+ ggsave(filename, path)
```
```{r}
#timeseries
#Make a time series plot (using ggfortify)
library(ggfortify)
autoplot(AirPassengers) + labs(title="AirPassengers")  # where AirPassengers is a 'ts' object
class(AirPassengers)

# Approach 2 uaing ggplot only
data(economics, package="ggplot2")  # init data
economics <- data.frame(economics)  # convert to dataframe
ggplot(economics) + geom_line(aes(x=date, y=pce, color="pcs")) + geom_line(aes(x=date, y=unemploy, col="unemploy")) + scale_color_discrete(name="Legend") + labs(title="Economics") # plot multiple time series using 'geom_line's

```

