---
title: "Important codes"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

###  import shp to sf and convert CRS
```{r eval=FALSE, include=FALSE}
#import shp files
area_sf <- st_read("D:/Projects/ENV Special Topic Paper/GIS/StudyArea.shp")
area_sf <- st_transform(area_sf, crs="+proj=longlat +datum=WGS84")
crs(area_sf)

```

### import shp to sp and convert CRS

```{r eval=FALSE, include=FALSE}

area_sp <- readOGR("D:/Projects/ENV Special Topic Paper/GIS/StudyArea.shp")
proj4string(area_sp) #check the CRS
#change to WGS
area_sp <- spTransform(area_sp, CRS("+proj=longlat +datum=WGS84"))
```


### import shp files to sf dataframe and convert to WGS

```{r eval=FALSE, include=FALSE}
# how to import shp files to sf dataframe and convert to WGS 
samp_random <- "D:/Projects/ENV Special Topic Paper/GIS/InsAR_randomsample.shp" %>%
  st_read() %>% st_transform(crs = "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs")
#convert sf geometry to x y column df, mutate and convert to df, remove na value
samp_random_xy <- do.call(rbind, st_geometry(samp_random)) %>% 
  as_tibble() %>% setNames(c("lon","lat")) 
samp_random <- samp_random %>% mutate(samp_random_xy) 
samp_random <- samp_random %>% as.data.frame() %>% na.omit()
#delete previous XY CRS column
samp_random[ , c("X", "Y", "geometry")] <- list(NULL)
```

### Open street map study area


```{r eval=FALSE, include=FALSE}
#create study area large zoom map
##defining the upper-left and lower-right corners (Y, X)
extent.area2 <- openmap(c(36,32), c(9,59), type = "esri" )
plot(extent.area2)
map.area2 <- openproj(extent.area2, projection = "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs" )
map.study <- autoplot.OpenStreetMap(map.area2)  +
  labs(title = "Study Area",x = "Longitude", y="Latitude") + 
  geom_polygon(aes(x = long, y = lat, group=id),
               data = area_sp, color ="red", fill ="orangered4",
               alpha = .04, size = 1) 
map.study

#create point location map 
extent.area <- openmap(c(30.5,38), c(29.3,39.15), type = "esri" )
plot(extent.area)
map.area <- openproj(extent.area, projection = "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs" )
map.random.point <- autoplot.OpenStreetMap(map.area)  +
  labs(title = "Random sample location",x = "Longitude", y="Latitude") + 
  geom_point(data = samp_random, aes(x = lon, y = lat, color = InSAR_Raw_), size = 0.5) + 
  scale_color_viridis_c(option = "plasma", name = "DS (cm)", na.value = "gray") + 
  geom_polygon(aes(x = long, y = lat, group=id),
             data = area_sp, color ="red", fill ="orangered4", alpha = 0.01, size = 2) 
map.random.point

#make plot side by side
library(cowplot)
plot_grid(map.study, map.random.point, labels = "AUTO", label_y = 0.8)
```

```{r}
library(tidyverse)
library(OpenStreetMap)
library(rgdal)
library(sf)

#samp random need to be changed, because the name is the same as in the hist.boxplot.R

#import shp files
area_sf <- st_read("D:/Projects/ENV Special Topic Paper/GIS/StudyArea.shp")
area_sf <- st_transform(area_sf, crs="+proj=longlat +datum=WGS84")
crs(area_sf)
#plot the point using Openstreet Map Esri (need to use dataframe and WGS crs)
#add Polygon from shapefile
#import shp as sp class
area_sp <- readOGR("D:/Projects/ENV Special Topic Paper/GIS/StudyArea.shp")
proj4string(area_sp) #check the CRS
#change to WGS
area_sp <- spTransform(area_sp, CRS("+proj=longlat +datum=WGS84"))


#create study area large zoom map
##defining the upper-left and lower-right corners (Y, X)
extent.area2 <- openmap(c(36,32), c(9,59), type = "esri" )
plot(extent.area2)
map.area2 <- openproj(extent.area2, projection = "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs" )
map.study <- autoplot.OpenStreetMap(map.area2)  +
  labs(title = "Study Area",x = "Longitude", y="Latitude") + 
  geom_polygon(aes(x = long, y = lat, group=id),
               data = area_sp, color ="red", fill ="orangered4",
               alpha = .04, size = 1) 
map.study

#plot the map using google Map API (ggmap) 
library(tidyverse)
library(ggmap)

#register google 
register_google(key = "AIzaSyBf0cxawzGkYzG8cpteTmBD3EQdCrsnRU0", write = TRUE)
#GGMAP bounding box lowerleftlon, lowerleftlat, upperrightlon, upperrightlat

mymap <- get_googlemap(center = c(lat = 38.5, lon = 29.9), 
                       maptype = "satellite", zoom = 9) %>% ggmap() + 
  geom_polygon(aes(x = long, y = lat, group=id), data = area_sp,
               color ="red", fill ="orangered4", alpha = 0.01, size = 2) + 
  labs(x = "Longitude", y="Latitude")

mymap
#make plot side by side
library(cowplot)
plot_grid(map.study, mymap, labels = "AUTO", label_y = 0.8)



```

